version: '3'
services:
  app:
    image: stegerpa/seafile7
    ports:
    - "80:80"
    stdin_open: true
    tty: true

  sast:
    container_name: sast_seafile
    build: sast_image/.
    ports:
    - "8888:8888"
    volumes:
      - .:/tmp/
    command: sh -c "flawfinder seafile/. > /tmp/flawfinder_res.txt"

  dast:
    container_name: dast_seafile
    build: dast_image/.
    volumes:
      - .:/tmp/
    ports:
    - "8889:8889"
    depends_on:
      - app
